[metadata]
name = censoring-aware-wind-power
version = 0.1.0
description = Censoring-aware probabilistic forecasting of wind-turbine potential available power
long_description = file: README.md
long_description_content_type = text/markdown
author = Kefan Chen
url = https://github.com/kefanchen-code/censoring-aware-wind-power-forecasting

[options]
package_dir =
    = src
packages = find:
python_requires = ==3.9.*
install_requires =
    matplotlib==3.4.3
    numpy==1.20.3
    pandas==1.3.4
    pyarrow==21.0.0
    scikit-learn==0.24.2
    scipy==1.7.1
    torch==2.8.0

[options.packages.find]
where = src
